version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usr
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_NAME: db
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7.42
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: usr
      MYSQL_PASSWORD: pwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  wordpress:
  db: